version: '3.8'

services:
  # Service 1: The "Chaos" Generator
  # Wakes up and creates fake data
  backend:
    build: .
    container_name: nexus_pipeline
    command: python src/backend/main.py
    volumes:
      - ./src/database/raw_data:/app/src/raw_data
      - ./src/backend:/app/src/backend
    environment:
      - PYTHONUNBUFFERED=1

  # Service 2: The Dashboard & Brain
  # Reads the data and runs the AI
  # dashboard:
  #   build: .
  #   container_name: nexus_dashboard
  #   command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
  #   volumes:
  #     - ./raw_data:/app/raw_data  # Reads from the same synced folder
  #     - ./database:/app/database  # Persists the DBs
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - generator
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}  # Passes your key safely